// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfsmkomhlkkribzvfawy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmc21rb21obGtrcmlienZmYXd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTQwMTgsImV4cCI6MjA2MzA3MDAxOH0.BF-TiQTwVdJAbq5eU22UR9wnzSfRPzGPCfIF98IfCd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);